version: "3.9"

services:
  database-order:
    image: postgres:16
    container_name: postgres_order
    volumes:
      - ./:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order
    ports:
      - "5435:5432"
    networks:
      - shared-network

  app:
    container_name: OrderService
    command: java -jar target/OrderService-1.0.0.jar
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database-order
    volumes:
      - ./:/app/app
    ports:
     - "1237:1237"
    networks:
      - shared-network
    environment:
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=user
      - spring_rabbitmq_password=password
      - spring.datasource.url=jdbc:postgresql://database-order:5432/order
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/ssds

networks:
  shared-network:
    external: true
