variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/backend/ProductService/.m2/repository"
  PRODUCT_SERVICE_DIR: backend/ProductService
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.9-dind

build_product_service:
  stage: build
  image: maven:3.9.8-eclipse-temurin-17
  before_script:
    - cd $PRODUCT_SERVICE_DIR
  script:
    - echo "Building Product Service"
    - mvn clean install -B -DskipTests
  artifacts:
    paths:
      - $PRODUCT_SERVICE_DIR/target/*.jar

test_product_service:
  stage: test
  image: maven:3.9.8-eclipse-temurin-17
  before_script:
    - cd $PRODUCT_SERVICE_DIR
  script:
    - echo "Testing Product Service"
    - mvn test -B